### ISSUE TITLE
Wrong license shown in https://anaconda.org/conda-forge/cleanlab

### ISSUE THREAD

**Issue by jwmueller** [conda-forge/cleanlab-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The website for this package: https://anaconda.org/conda-forge/cleanlab
Shows it as MIT License. But the correct license is AGPL-3.0.

![Screen Shot 2023-05-12 at 9 37 41 PM](https://github.com/conda-forge/cleanlab-feedstock/assets/1390638/a6ebbc5f-d734-4b90-8429-26c7a2e5522c)

This cleanlab-feedstock repo lists the correct license so I'm not sure why anaconda.org is showing MIT license:

![Screen Shot 2023-05-12 at 9 48 18 PM](https://github.com/conda-forge/cleanlab-feedstock/assets/1390638/527bc410-6405-4398-8de4-f3b7552e25eb)

### Installed packages

```shell
doesnt matter
```

### Environment info

```shell
doesnt matter
```

**Comment by BastianZim** [comment]
This is due to conda and not this feedstock itself. Unfortunately, there is nothing that can be done here.
There is an ongoing discussion here if you would like to follow/voice concern: https://github.com/conda/infrastructure/discussions/649

**Comment by jwmueller** [comment]
Got it, thank you for the pointer!
